######################################################################
# Automatically generated by qmake (3.0) Wed Feb 24 16:44:28 2016
######################################################################
include(../defaults.pri)

TEMPLATE = app
QT += core testlib sql gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
TARGET = test
CONFIG +=console
CONFIG += app_bundle
INCLUDEPATH += .

# Input
HEADERS += test_database.h \
    test_gui.h
SOURCES += test_database.cpp

LIBS += -L../src -lfast-food-app
