######################################################################
# Automatically generated by qmake (3.0) Wed Feb 24 16:44:28 2016
######################################################################
include(../defaults.pri)

TEMPLATE = app
QT += testlib sql
TARGET = test
CONFIG +=console
CONFIG += app_bundle
INCLUDEPATH += .

# Input
HEADERS += test_database.h
SOURCES += test_database.cpp \
    test_mainwindow.cpp

LIBS += -L../src -lfast-food-app
