######################################################################
# Automatically generated by qmake (3.0) Wed Feb 24 16:44:28 2016
######################################################################

QT += testlib
TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
HEADERS += test_database.h
SOURCES += test_database.cpp
