INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (1, 'Big Mac', 3.99, 1);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (1, 'French Fries', 2.99, 2);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (1, 'Hamburger', 1.79, 3);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (1, 'Double Cheeseburger', 4.29, 4);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (1, 'Cheeseburger', 2.29, 5);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (1, 'Quarter Pounder with Cheese', 4.99, 6);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (1, 'Filet-O-Fish', 3.33, 7);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (1, 'McRib', 4.97, 8);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (2, 'Veggie Taco', 5.99, 9);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (2, 'Veggie Burrito', 7.99, 10);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (2, 'Steak Taco', 3.99, 11);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (2, 'Steak Burrito', 8.99, 12);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (2, 'Chicken Taco', 4.99, 13);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (2, 'Chicken Burrito', 6.99, 14);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (3, 'Veggie Pizza', 9.99, 15);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (3, 'Pepperoni Pizza', 8.99, 16);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (3, 'All-Meat Pizza', 12.99, 17);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (3, 'Cheese Pizza', 5.99, 18);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (3, 'Mushroom and Pepperoni Pizza', 7.99, 19);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (4, 'Three Piece Original Fried Chicken', 6.99, 20);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (4, 'Bucket of Crispy Fried Chicken', 13.99, 21);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (4, 'Mashed Potatoes', 5.99, 22);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (4, 'Cole Slaw', 5.99, 23);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (4, 'The Bones', 0.03, 24);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (5, 'Veggie Delite', 4.99, 25);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (5, 'Tuna Sandwich', 4.99, 26);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (5, 'Spicy Italian', 7.99, 27);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (5, 'Turkey Sandwich', 5.99, 28);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (6, 'Hamburger', 2.99, 29);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (6, 'Cheeseburger', 3.29, 30);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (6, 'Milkshake', 2.99, 31);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (6, 'French Fries', 1.79, 32);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (6, 'Medium Coke', 2.35, 33);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (7, 'Hamburger', 3.99, 34);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (7, 'Cheeseburger', 4.29, 35);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (7, 'Small Classic Chocolate Frosty', 2.99, 36);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (7, 'French Fries', 1.79, 37);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (7, 'Chicken Wrap', 4.39, 38);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (8, 'Chicken Club Salad', 6.99, 39);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (8, 'Southwest Chicken Salad', 7.29, 40);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (8, 'Grilled Chicken Salad', 5.99, 41);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (8, 'Side Salad', 1.79, 42);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (8, 'Sourdough Jack', 5.99, 43);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (8, 'Greasy Wallet', 1.29, 44);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (9, 'Monterey Pollo Salad', 6.99, 45);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (9, 'Steamed Vegetables', 3.29, 46);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (9, 'Chicken Tortilla Soup', 5.29, 47);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (9, 'A Whole Chicken', 7.99, 48);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (9, 'Fried Gizzard Taco', 3.29, 49);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (9, 'BRC Burrito', 0.79, 50);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (10, 'Veggie Pizza', 4.09, 51);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (10, 'Pepperoni Pizza', 8.99, 52);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (10, 'All-Meat Pizza', 12.99, 53);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (10, 'Cheese Pizza', 5.99, 54);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (10, 'Mushroom and Pepperoni Pizza', 6.99, 55);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (11, 'Veggie Pizza', 4.99, 56);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (11, 'Pepperoni Pizza', 8.99, 57);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (11, 'All-Meat Pizza', 12.99, 58);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (11, 'Cheese Pizza', 5.99, 59);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (11, 'Mushroom and Pepperoni Pizza', 6.99, 60);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (11, 'Mushroom and Green Pepper Pizza', 7.29, 61);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (12, 'Sonic Hamburger', 3.99, 62);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (12, 'Sonic Cheeseburger', 4.29, 63);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (12, 'New York Dog', 2.89, 64);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (12, 'French Fries', 1.79, 65);
INSERT INTO fast_food_restaurants.items (id, name, price, itemId) VALUES (12, 'Medium Pepsi', 2.55, 66);